//! PyO3 binding for m3s-core. Exposes each grid's cell functions returning plain
//! `(id, ring, precision)` tuples; the Python side wraps these into `GridCell`.
//! Module name: `m3s_core`.
//!
//! The per-grid wrappers are generated by `grid_base!` / `grid_hierarchy!` from a
//! single line per grid (see the invocations below): the core keeps free
//! functions (no trait, ADR 0001 §8), and this macro removes the hand-written
//! boilerplate without adding any runtime dispatch.

use ::m3s_core::{
    a5_grid as a5, csquares_grid as cs, eaquad_grid as eaq, gars_grid as gars, geohash_grid as gh,
    h3_grid as h3, maidenhead_grid as mh, mgrs_grid as mgrs, pluscode_grid as pc,
    quadkey_grid as qk, s2_grid as s2, slippy_grid as sl, Cell,
};
use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use std::collections::HashMap;

/// `(id, [(lon, lat), ...], precision)` — the shape the Python parity layer reads.
type PyCell = (String, Vec<(f64, f64)>, u8);

fn to_py(c: Cell) -> PyCell {
    let ring = c.ring.into_iter().map(|p| (p[0], p[1])).collect();
    (c.id, ring, c.precision)
}

fn to_py_vec(cells: Vec<Cell>) -> Vec<PyCell> {
    cells.into_iter().map(to_py).collect()
}

fn err(e: String) -> PyErr {
    PyValueError::new_err(e)
}

/// The four operations every grid exposes: `{prefix}_cell_from_point`,
/// `_cell_from_id`, `_neighbors`, `_cells_in_bbox`. `$p` is both the module alias
/// (`gh::cell_from_point`) and the Python function-name prefix (`gh_...`).
macro_rules! grid_base {
    ($p:ident) => {
        ::paste::paste! {
            #[pyfunction]
            fn [<$p _cell_from_point>](lat: f64, lon: f64, precision: u8) -> PyResult<PyCell> {
                $p::cell_from_point(lat, lon, precision).map(to_py).map_err(err)
            }
            #[pyfunction]
            fn [<$p _cell_from_id>](id: &str) -> PyResult<PyCell> {
                $p::cell_from_id(id).map(to_py).map_err(err)
            }
            #[pyfunction]
            fn [<$p _neighbors>](id: &str) -> PyResult<Vec<PyCell>> {
                $p::neighbors(id).map(to_py_vec).map_err(err)
            }
            #[pyfunction]
            fn [<$p _cells_in_bbox>](
                min_lat: f64,
                min_lon: f64,
                max_lat: f64,
                max_lon: f64,
                precision: u8,
            ) -> PyResult<Vec<PyCell>> {
                $p::cells_in_bbox(min_lat, min_lon, max_lat, max_lon, precision)
                    .map(to_py_vec)
                    .map_err(err)
            }
        }
    };
}

/// `{prefix}_children` / `{prefix}_parent`, only for hierarchical grids.
macro_rules! grid_hierarchy {
    ($p:ident) => {
        ::paste::paste! {
            #[pyfunction]
            fn [<$p _children>](id: &str) -> PyResult<Vec<PyCell>> {
                $p::children(id).map(to_py_vec).map_err(err)
            }
            #[pyfunction]
            fn [<$p _parent>](id: &str) -> PyResult<PyCell> {
                $p::parent(id).map(to_py).map_err(err)
            }
        }
    };
}

// Hierarchical grids: base + children/parent.
grid_base!(gh);
grid_hierarchy!(gh);
grid_base!(h3);
grid_hierarchy!(h3);
grid_base!(qk);
grid_hierarchy!(qk);
grid_base!(sl);
grid_hierarchy!(sl);
grid_base!(cs);
grid_hierarchy!(cs);
grid_base!(pc);
grid_hierarchy!(pc);
grid_base!(a5);
grid_hierarchy!(a5);
grid_base!(eaq);
grid_hierarchy!(eaq);
grid_base!(s2);
grid_hierarchy!(s2);

// Non-hierarchical grids: base only (no children/parent).
grid_base!(gars);
grid_base!(mh);
grid_base!(mgrs);

// a5-only extra: A5 is equal-area, so a resolution has one exact cell area.
#[pyfunction]
fn a5_cell_area_m2(precision: u8) -> f64 {
    a5::cell_area_m2(precision)
}

// ---- shared -----------------------------------------------------------------

#[pyfunction]
fn geodesic_area_km2(ring: Vec<(f64, f64)>) -> f64 {
    let ring: Vec<[f64; 2]> = ring.into_iter().map(|(a, b)| [a, b]).collect();
    ::m3s_core::geodesic_area_km2(&ring)
}

/// `{name: (min, max, default)}` precision bounds for every grid, keyed by
/// canonical grid name — the registry's single source of truth (ADR 0001 P4).
#[pyfunction]
fn all_precision_bounds() -> HashMap<String, (u8, u8, u8)> {
    ::m3s_core::all_precision_bounds()
        .into_iter()
        .map(|(name, mn, mx, d)| (name.to_string(), (mn, mx, d)))
        .collect()
}

/// Register `{prefix}_*` functions on the module, mirroring the macros above.
macro_rules! reg_base {
    ($m:expr, $p:ident) => {
        ::paste::paste! {
            $m.add_function(wrap_pyfunction!([<$p _cell_from_point>], $m)?)?;
            $m.add_function(wrap_pyfunction!([<$p _cell_from_id>], $m)?)?;
            $m.add_function(wrap_pyfunction!([<$p _neighbors>], $m)?)?;
            $m.add_function(wrap_pyfunction!([<$p _cells_in_bbox>], $m)?)?;
        }
    };
}

macro_rules! reg_hierarchy {
    ($m:expr, $p:ident) => {
        ::paste::paste! {
            $m.add_function(wrap_pyfunction!([<$p _children>], $m)?)?;
            $m.add_function(wrap_pyfunction!([<$p _parent>], $m)?)?;
        }
    };
}

#[pymodule]
fn m3s_core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    reg_base!(m, gh);
    reg_hierarchy!(m, gh);
    reg_base!(m, h3);
    reg_hierarchy!(m, h3);
    reg_base!(m, qk);
    reg_hierarchy!(m, qk);
    reg_base!(m, sl);
    reg_hierarchy!(m, sl);
    reg_base!(m, cs);
    reg_hierarchy!(m, cs);
    reg_base!(m, pc);
    reg_hierarchy!(m, pc);
    reg_base!(m, a5);
    reg_hierarchy!(m, a5);
    reg_base!(m, eaq);
    reg_hierarchy!(m, eaq);
    reg_base!(m, s2);
    reg_hierarchy!(m, s2);
    reg_base!(m, gars);
    reg_base!(m, mh);
    reg_base!(m, mgrs);
    m.add_function(wrap_pyfunction!(a5_cell_area_m2, m)?)?;
    m.add_function(wrap_pyfunction!(geodesic_area_km2, m)?)?;
    m.add_function(wrap_pyfunction!(all_precision_bounds, m)?)?;
    Ok(())
}
