//! wasm-bindgen binding for m3s-core. Returns cells as JS objects
//! `{ id, ring: [[lon,lat],...], precision }` — the shape the deck.gl examples
//! in `examples/grid_systems/_grids/*.js` consume.
//!
//! Per-grid wrappers are generated by `grid_base!` / `grid_hierarchy!` from a
//! single line per grid; the core keeps free functions (no trait, ADR 0001 §8)
//! and the macro removes the hand-written boilerplate.

use m3s_core::{
    a5_grid as a5, csquares_grid as cs, eaquad_grid as eaq, gars_grid as gars, geohash_grid as gh,
    h3_grid as h3, maidenhead_grid as mh, mgrs_grid as mgrs, pluscode_grid as pc,
    quadkey_grid as qk, s2_grid as s2, slippy_grid as sl, Cell,
};
use serde::Serialize;
use std::collections::HashMap;
use wasm_bindgen::prelude::*;

#[derive(Serialize)]
struct JsCell {
    id: String,
    ring: Vec<[f64; 2]>,
    precision: u8,
}

impl From<Cell> for JsCell {
    fn from(c: Cell) -> Self {
        JsCell {
            id: c.id,
            ring: c.ring,
            precision: c.precision,
        }
    }
}

fn ok<T: Serialize>(v: T) -> Result<JsValue, JsValue> {
    serde_wasm_bindgen::to_value(&v).map_err(|e| JsValue::from_str(&e.to_string()))
}

fn cell(r: Result<Cell, String>) -> Result<JsValue, JsValue> {
    r.map(JsCell::from)
        .map_err(|e| JsValue::from_str(&e))
        .and_then(ok)
}

fn cells(r: Result<Vec<Cell>, String>) -> Result<JsValue, JsValue> {
    r.map(|cs| cs.into_iter().map(JsCell::from).collect::<Vec<_>>())
        .map_err(|e| JsValue::from_str(&e))
        .and_then(ok)
}

/// The four operations every grid exposes. `$p` is both the module alias and the
/// exported function-name prefix (`gh_cell_from_point`).
macro_rules! grid_base {
    ($p:ident) => {
        ::paste::paste! {
            #[wasm_bindgen]
            pub fn [<$p _cell_from_point>](lat: f64, lon: f64, precision: u8) -> Result<JsValue, JsValue> {
                cell($p::cell_from_point(lat, lon, precision))
            }
            #[wasm_bindgen]
            pub fn [<$p _cell_from_id>](id: &str) -> Result<JsValue, JsValue> {
                cell($p::cell_from_id(id))
            }
            #[wasm_bindgen]
            pub fn [<$p _neighbors>](id: &str) -> Result<JsValue, JsValue> {
                cells($p::neighbors(id))
            }
            #[wasm_bindgen]
            pub fn [<$p _cells_in_bbox>](
                min_lat: f64,
                min_lon: f64,
                max_lat: f64,
                max_lon: f64,
                precision: u8,
            ) -> Result<JsValue, JsValue> {
                cells($p::cells_in_bbox(min_lat, min_lon, max_lat, max_lon, precision))
            }
        }
    };
}

/// `{prefix}_children` / `{prefix}_parent`, only for hierarchical grids.
macro_rules! grid_hierarchy {
    ($p:ident) => {
        ::paste::paste! {
            #[wasm_bindgen]
            pub fn [<$p _children>](id: &str) -> Result<JsValue, JsValue> {
                cells($p::children(id))
            }
            #[wasm_bindgen]
            pub fn [<$p _parent>](id: &str) -> Result<JsValue, JsValue> {
                cell($p::parent(id))
            }
        }
    };
}

// Hierarchical grids: base + children/parent.
grid_base!(gh);
grid_hierarchy!(gh);
grid_base!(h3);
grid_hierarchy!(h3);
grid_base!(qk);
grid_hierarchy!(qk);
grid_base!(sl);
grid_hierarchy!(sl);
grid_base!(cs);
grid_hierarchy!(cs);
grid_base!(pc);
grid_hierarchy!(pc);
grid_base!(a5);
grid_hierarchy!(a5);
grid_base!(eaq);
grid_hierarchy!(eaq);
grid_base!(s2);
grid_hierarchy!(s2);

// Non-hierarchical grids: base only.
grid_base!(gars);
grid_base!(mh);
grid_base!(mgrs);

// ---- shared -----------------------------------------------------------------

#[wasm_bindgen]
pub fn geodesic_area_km2(ring: JsValue) -> Result<f64, JsValue> {
    let ring: Vec<[f64; 2]> =
        serde_wasm_bindgen::from_value(ring).map_err(|e| JsValue::from_str(&e.to_string()))?;
    Ok(m3s_core::geodesic_area_km2(&ring))
}

/// `{name: [min, max, default]}` precision bounds for every grid, keyed by
/// canonical grid name — the registry's single source of truth (ADR 0001 P4),
/// identical to the Python binding's `all_precision_bounds`.
#[wasm_bindgen]
pub fn all_precision_bounds() -> Result<JsValue, JsValue> {
    let map: HashMap<String, [u8; 3]> = m3s_core::all_precision_bounds()
        .into_iter()
        .map(|(name, mn, mx, d)| (name.to_string(), [mn, mx, d]))
        .collect();
    ok(map)
}
